server:
  port: 8080

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/sber
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

user:
  birthday:
    format: yyyy-MM-dd

sber:
  cloud:
    key: OMAVJLD9AL6GZQMV52FO
    secret: fKdRahYKIr45Es1ekoBrUCf3VsAhl4nM7baI5oYq
    username: hackathon101
    projectId: 0b9654864a0024ab2f81c01da83988dc
    cloudEye-endpoint: ces.ru-moscow-1.hc.sbercloud.ru
