server:
  port: 8080

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/sber
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

user:
  birthday:
    format: yyyy-MM-dd
